name: Release - Reusable Workflow
on:
  workflow_call:
    secrets:
      GITHUB_PAT:
        required: true
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Harden Security
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_PAT }}
          release-type: node
