name: Release - Reusable Workflow
on:
  push:
    branches: [main]

permissions: read-all

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Harden Security
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GH_PAT }}
          release-type: node
